#!/usr/bin/env python
#
# GIT version. Please do not edit this file.
# Make a copy and edit the copy.
#

import sys
import os


# L = <list of experiments to compare and label to use in the plot (no spaces allowed in the label!!!)>

L = []


# Read file with experiments to plot

if (len(sys.argv)<4):
    print "Use: do_plot_last_exp.py <num of last exp to plot> <plot title> <label_1> ... <label_n>"
    sys.exit(0)

exptoplot = "exptoplot.txt"
ntoplot = sys.argv[1]
cmd = "tail -n "+ntoplot+" experiments.txt > " + exptoplot
os.system(cmd)

plot_title = sys.argv[2]
outfile = '"'+plot_title+'.pdf"'

k = 3; # index for the labels

#print "File with exp to plot: ",exptoplot

f = open(exptoplot,'r')

for line in f:
    e = line.rstrip('\r\n ')
    L.append(e)
    L.append(sys.argv[k])
    k=k+1

f.close

# Run the R script



for i in range(0,len(L)/2):
  plot_title_2 = '"' + plot_title.strip('"') + ' ' + L[i*2+1] + '"'

  print plot_title_2

  precmd = 'Rscript stats/plots.R '+plot_title_2+' '
  cmd = precmd + "%s_idleness.csv %s " %(L[i*2],L[i*2+1])
  os.system(cmd)
  
  outfile = '"' + plot_title.strip('"') + '_' + L[i*2+1] + '.pdf"'
  cmd = 'mv Rplots.pdf '+outfile
  os.system(cmd)

  cmd = 'evince '+outfile+ ' &'
  os.system(cmd)

